### ISSUE TITLE
Package missing from npm

### ISSUE THREAD

**Issue by roumcha** [astro-community/astro-compress#162]
The astro-compress package is missing from npm. Has it been withdrawn?
<https://www.npmjs.com/package/astro-compress>

**Comment by NikolaRHristov** [comment]
Hi, no, I've just deleted my NPM account. I should've put more thought into it, because I was archiving my GitHub and NPM. I'll release a new one shortly, meanwhile, the source is available at the repo and here https://github.com/NikolaRHristov/NikolaRHristov

Dependencies:

Lightrix/NPM and Lightrix/files-pipe

Apologies for the downtime.

**Comment by roumcha** [comment]
Thank you for the update! No problem about the downtime. I created this issue just in case there were any problems.

**Comment by mwaldheim** [comment]
How long will it take? My website is down now... because my pipeline can't do a rebuild.
